### ISSUE TITLE
Side-by-side document viewer

### ISSUE THREAD

**Issue by mbelousov** [healtex/texscrubber#13]
Synchronised scrolling between original and annotated text.

GATEDoc XML -> Deserialise into GATEDoc
Original text: Content of GDoc
Annotated result:  -> Annotations from GDoc + original text property

**Comment by mbelousov** [comment]
Should be sufficient to have one viewer with annotated document (highlighted)

**Comment by RichJackson** [comment]
Was thinking about this a bit more. I think we should ditch the idea of doing this in our custom GUI, because it's a reinvention of the wheel. The docs can just as easily be viewed with the GATE GUI, if the output is just  GATE XML. Why don't I focus on finishing the basic launcher interface, and then start on the webserver version? Otherwise it's potentially a lot of work for a small project

**Comment by mbelousov** [comment]
@RichJackson , agree, we came to exactly the same conclusion with @dehghana the other day.
