### ISSUE TITLE
NamedEntityExtractor component

### ISSUE THREAD

**Issue by mbelousov** [healtex/texscrubber#4]
Extracts all named entities from unannotated GATEDocument and generates annotated GATEDocument

**Comment by dehghana** [comment]
Assuming this issue is: Applying DEID NERs on an unannotated gate.Document and generate annotated gate.Document

**Comment by hkkenneth** [comment]
@dehghana To start integrating this GATE pipeline with Spring batch, can we call this extractor from `FirstPassItemProcessor.process()` to make sure it can run?

Let's keep the dummy output of processor unchanged for now. Based on this integration, I can then make the transition to `gate.GATEDocument` so that other people can work on the rest of the pipeline.
